- name: Utility
  hosts: localhost
  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: aieie
          #- name: update
          #ansible.builtin.apt:
          #update-cache: yes
    - name: tldr
      ansible.builtin.apt:
        name: tldr
    - name: kubect-propsl
      ansible.builtin.apt:
        name: apt-transport-https
        name: ca-certificates
        name: curl
    - name: ci riprovo
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg      
    - name: kube-repo-boh
      become: true
      shell:  echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
         
        #- name: update
        # ansible.builtin.apt: 
        #update_cache=yes  force_apt_get=yes
      
    - name: install-kube
      ansible.builtin.apt:
        name: kubectl
    - name: Creates directory
      ansible.builtin.file:
        path:  ~/.kube
        state: directory
      
    - name: Copykubconfig
      ansible.builtin.copy:
        src: configs/kube/k3s.txt
        dest: ~/.kube/confi
          
    - name: InstallK9s      
      shell: curl -LO https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
    
    - name: deGZ
      shell: tar xf k9s_Linux_amd64.tar.gz
    
    - name: 
      become: true
      ansible.builtin.copy:
        src: ./k9s
        dest: /usr/local/bin    
        mode: 0777  
